// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { ProviderId } from "./ProviderId";

export type ProviderProfile = { id: ProviderId, baseUrl: string | null, model: string, requestOverrides: JsonValue, };
