// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestParameterError = { path: string, message: string, line: number | null, column: number | null, };
